---
- name: Install openvpn and easy-rsa
  yum:
    name : 
      - openvpn
      - expect    # this playbook needs it for easy-rsa
    state : present
  when: ansible_distribution == "Ubuntu"

- name: get easyRSA the other way for Ubuntu
  unarchive:
     src: https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.8/EasyRSA-3.0.8.tgz
     dest: /etc/openvpn/
     remote_src: yes
  when: ansible_distribution == "Ubuntu"

- name: link EasyRSA-3.0.8 to easy-rsa
  file:
    src: /etc/openvpn/EasyRSA-3.0.8
    dest: /etc/openvpn/easy-rsa
    state: link
  when: ansible_distribution == "Ubuntu"

- name: set easy-rsa default key timeout to nine years
  lineinfile:
    path: /etc/openvpn/easy-rsa/easyrsa
    regexp: 'set_var EASYRSA_CERT_EXPIRE'
    line: '        set_var EASYRSA_CERT_EXPIRE     3285 # default of 9 years'
