---
- name: update all
  apt: 
    name: "*"
    state: latest
    update_cache: yes

- name: Install myriad packages required by build
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - p7zip-full
    - wget
    - zip
    - unzip
    - autossh
    - pv
    - htop
    - sysstat
    - figlet
    - telnet
    - coreutils
    - m4
    - autoconf
    - autotools-dev
    - automake
    - binutils-common
    - libbinutils
    - binutils-x86-64-linux-gnu
    - binutils
    - libc-dev-bin
    - linux-libc-dev
    - libc6-dev
    - gcc-7-base
    - libisl19
    - libmpc3
    - cpp-7
    - cpp
    - libcc1-0
    - libgomp1
    - libitm1
    - libatomic1
    - libasan4
    - liblsan0
    - libtsan0
    - libubsan0
    - libcilkrts5
    - libmpx2
    - libquadmath0
    - libgcc-7-dev
    - gcc-7
    - gcc
    - libstdc++-7-dev
    - g++-7
    - g++
    - make
    - libdpkg-perl
    - dpkg-dev
    - build-essential
    - cmake-data
    - libarchive13
    - libjsoncpp1
    - librhash0
    - cmake
    - libfakeroot
    - fakeroot
    - libalgorithm-diff-perl
    - libalgorithm-diff-xs-perl
    - libalgorithm-merge-perl
    - libfile-fcntllock-perl
    - libltdl7
    - libltdl-dev
    - liblzo2-dev
    - libpam0g-dev
    - libssl-dev
    - libtool
    - man2html-base
    - man2html
    - manpages-dev
    - ninja-build
    - nsis-common
    - nsis
    - pkg-config
    - ssl-cert
    - unzip
    - binutils-mingw-w64-i686
    - binutils-mingw-w64-x86-64
    - dos2unix
    - mingw-w64-common
    - mingw-w64-i686-dev
    - gcc-mingw-w64-base
    - gcc-mingw-w64-i686
    - mingw-w64-x86-64-dev
    - gcc-mingw-w64-x86-64
    - gcc-mingw-w64
    - liblz4-dev
    - libpython2.7-minimal
    - python2.7-minimal
    - python-minimal
    - libpython2.7-stdlib
    - python2.7
    - libpython-stdlib
    - python
    - python-apt
    - linux-modules-5.4.0-1057-aws
    - linux-image-5.4.0-1057-aws
    - linux-aws-5.4-headers-5.4.0-1057
    - linux-headers-5.4.0-1057-aws
    - libllvm6.0
    - libclang1-6.0
    - libxapian30
    - doxygen
    - fonts-dejavu-core
    - fonts-liberation
    - fontconfig-config
    - libfontconfig1
    - fontconfig
    - libjpeg-turbo8
    - x11-common
    - libice6
    - libsm6
    - libann0
    - libcdt5
    - libcgraph6
    - libjpeg8
    - libjbig0
    - libtiff5
    - libwebp6
    - libxpm4
    - libgd3
    - libgts-0.7-5
    - libpixman-1-0
    - libxcb-render0
    - libxcb-shm0
    - libxrender1
    - libcairo2
    - libthai-data
    - libdatrie1
    - libthai0
    - libpango-1.0-0
    - libgraphite2-3
    - libharfbuzz0b
    - libpangoft2-1.0-0
    - libpangocairo-1.0-0
    - libpathplan4
    - libgvc6
    - libgvpr2
    - liblab-gamut1
    - libxt6
    - libxmu6
    - libxaw7
    - graphviz
    - libgts-bin