---
- name: Get the build output
  fetch:
    src: ~/code/openvpn/build/build_out.txt
    dest: results/build_out.txt
  become: no

- name: Get the linux binaries
  fetch:
    src: ~/code/openvpn/build/pq-openvpn-linux-staged.tar.gz
    dest: results/pq-openvpn-linux-staged.tar.gz
  become: no

- name: Get the Windows OpenVPN GUI installer
  fetch:
    src: ~/code/openvpn/build/openvpn-install-2.4.9-I601-Win10.exe
    dest: results/openvpn-install-2.4.9-I601-Win10.exe
  become: no


    